// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: entpb/entpb.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogRequest_View int32

const (
	GetCatalogRequest_VIEW_UNSPECIFIED GetCatalogRequest_View = 0
	GetCatalogRequest_BASIC            GetCatalogRequest_View = 1
	GetCatalogRequest_WITH_EDGE_IDS    GetCatalogRequest_View = 2
)

// Enum value maps for GetCatalogRequest_View.
var (
	GetCatalogRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	GetCatalogRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x GetCatalogRequest_View) Enum() *GetCatalogRequest_View {
	p := new(GetCatalogRequest_View)
	*p = x
	return p
}

func (x GetCatalogRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCatalogRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[0].Descriptor()
}

func (GetCatalogRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[0]
}

func (x GetCatalogRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCatalogRequest_View.Descriptor instead.
func (GetCatalogRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2, 0}
}

type ListCatalogRequest_View int32

const (
	ListCatalogRequest_VIEW_UNSPECIFIED ListCatalogRequest_View = 0
	ListCatalogRequest_BASIC            ListCatalogRequest_View = 1
	ListCatalogRequest_WITH_EDGE_IDS    ListCatalogRequest_View = 2
)

// Enum value maps for ListCatalogRequest_View.
var (
	ListCatalogRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "WITH_EDGE_IDS",
	}
	ListCatalogRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"WITH_EDGE_IDS":    2,
	}
)

func (x ListCatalogRequest_View) Enum() *ListCatalogRequest_View {
	p := new(ListCatalogRequest_View)
	*p = x
	return p
}

func (x ListCatalogRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListCatalogRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_entpb_entpb_proto_enumTypes[1].Descriptor()
}

func (ListCatalogRequest_View) Type() protoreflect.EnumType {
	return &file_entpb_entpb_proto_enumTypes[1]
}

func (x ListCatalogRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListCatalogRequest_View.Descriptor instead.
func (ListCatalogRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5, 0}
}

type Catalog struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_entpb_entpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Catalog) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       *Catalog               `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogRequest) Reset() {
	*x = CreateCatalogRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogRequest) ProtoMessage() {}

func (x *CreateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCatalogRequest) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	View          GetCatalogRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=entpb.GetCatalogRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatalogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCatalogRequest) GetView() GetCatalogRequest_View {
	if x != nil {
		return x.View
	}
	return GetCatalogRequest_VIEW_UNSPECIFIED
}

type UpdateCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       *Catalog               `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogRequest) Reset() {
	*x = UpdateCatalogRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogRequest) ProtoMessage() {}

func (x *UpdateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCatalogRequest) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

type DeleteCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogRequest) Reset() {
	*x = DeleteCatalogRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogRequest) ProtoMessage() {}

func (x *DeleteCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCatalogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCatalogRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PageSize      int32                   `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                  `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	View          ListCatalogRequest_View `protobuf:"varint,3,opt,name=view,proto3,enum=entpb.ListCatalogRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogRequest) Reset() {
	*x = ListCatalogRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogRequest) ProtoMessage() {}

func (x *ListCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{5}
}

func (x *ListCatalogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCatalogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCatalogRequest) GetView() ListCatalogRequest_View {
	if x != nil {
		return x.View
	}
	return ListCatalogRequest_VIEW_UNSPECIFIED
}

type ListCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogList   []*Catalog             `protobuf:"bytes,1,rep,name=catalog_list,json=catalogList,proto3" json:"catalog_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogResponse) Reset() {
	*x = ListCatalogResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogResponse) ProtoMessage() {}

func (x *ListCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{6}
}

func (x *ListCatalogResponse) GetCatalogList() []*Catalog {
	if x != nil {
		return x.CatalogList
	}
	return nil
}

func (x *ListCatalogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchCreateCatalogsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Requests      []*CreateCatalogRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCatalogsRequest) Reset() {
	*x = BatchCreateCatalogsRequest{}
	mi := &file_entpb_entpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCatalogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCatalogsRequest) ProtoMessage() {}

func (x *BatchCreateCatalogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCatalogsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateCatalogsRequest) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreateCatalogsRequest) GetRequests() []*CreateCatalogRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchCreateCatalogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateCatalogsResponse) Reset() {
	*x = BatchCreateCatalogsResponse{}
	mi := &file_entpb_entpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateCatalogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateCatalogsResponse) ProtoMessage() {}

func (x *BatchCreateCatalogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_entpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateCatalogsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateCatalogsResponse) Descriptor() ([]byte, []int) {
	return file_entpb_entpb_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateCatalogsResponse) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

var File_entpb_entpb_proto protoreflect.FileDescriptor

const file_entpb_entpb_proto_rawDesc = "" +
	"\n" +
	"\x11entpb/entpb.proto\x12\x05entpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x83\x01\n" +
	"\aCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"@\n" +
	"\x14CreateCatalogRequest\x12(\n" +
	"\acatalog\x18\x01 \x01(\v2\x0e.entpb.CatalogR\acatalog\"\x92\x01\n" +
	"\x11GetCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x121\n" +
	"\x04view\x18\x02 \x01(\x0e2\x1d.entpb.GetCatalogRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"@\n" +
	"\x14UpdateCatalogRequest\x12(\n" +
	"\acatalog\x18\x01 \x01(\v2\x0e.entpb.CatalogR\acatalog\"&\n" +
	"\x14DeleteCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc0\x01\n" +
	"\x12ListCatalogRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x122\n" +
	"\x04view\x18\x03 \x01(\x0e2\x1e.entpb.ListCatalogRequest.ViewR\x04view\":\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\x11\n" +
	"\rWITH_EDGE_IDS\x10\x02\"p\n" +
	"\x13ListCatalogResponse\x121\n" +
	"\fcatalog_list\x18\x01 \x03(\v2\x0e.entpb.CatalogR\vcatalogList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"U\n" +
	"\x1aBatchCreateCatalogsRequest\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.entpb.CreateCatalogRequestR\brequests\"I\n" +
	"\x1bBatchCreateCatalogsResponse\x12*\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x0e.entpb.CatalogR\bcatalogs2\x83\x03\n" +
	"\x0eCatalogService\x125\n" +
	"\x06Create\x12\x1b.entpb.CreateCatalogRequest\x1a\x0e.entpb.Catalog\x12/\n" +
	"\x03Get\x12\x18.entpb.GetCatalogRequest\x1a\x0e.entpb.Catalog\x125\n" +
	"\x06Update\x12\x1b.entpb.UpdateCatalogRequest\x1a\x0e.entpb.Catalog\x12=\n" +
	"\x06Delete\x12\x1b.entpb.DeleteCatalogRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04List\x12\x19.entpb.ListCatalogRequest\x1a\x1a.entpb.ListCatalogResponse\x12T\n" +
	"\vBatchCreate\x12!.entpb.BatchCreateCatalogsRequest\x1a\".entpb.BatchCreateCatalogsResponseBCZAgithub.com/abisalde/gprc-microservice/catalog/pkg/ent/proto/entpbb\x06proto3"

var (
	file_entpb_entpb_proto_rawDescOnce sync.Once
	file_entpb_entpb_proto_rawDescData []byte
)

func file_entpb_entpb_proto_rawDescGZIP() []byte {
	file_entpb_entpb_proto_rawDescOnce.Do(func() {
		file_entpb_entpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)))
	})
	return file_entpb_entpb_proto_rawDescData
}

var file_entpb_entpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_entpb_entpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_entpb_entpb_proto_goTypes = []any{
	(GetCatalogRequest_View)(0),         // 0: entpb.GetCatalogRequest.View
	(ListCatalogRequest_View)(0),        // 1: entpb.ListCatalogRequest.View
	(*Catalog)(nil),                     // 2: entpb.Catalog
	(*CreateCatalogRequest)(nil),        // 3: entpb.CreateCatalogRequest
	(*GetCatalogRequest)(nil),           // 4: entpb.GetCatalogRequest
	(*UpdateCatalogRequest)(nil),        // 5: entpb.UpdateCatalogRequest
	(*DeleteCatalogRequest)(nil),        // 6: entpb.DeleteCatalogRequest
	(*ListCatalogRequest)(nil),          // 7: entpb.ListCatalogRequest
	(*ListCatalogResponse)(nil),         // 8: entpb.ListCatalogResponse
	(*BatchCreateCatalogsRequest)(nil),  // 9: entpb.BatchCreateCatalogsRequest
	(*BatchCreateCatalogsResponse)(nil), // 10: entpb.BatchCreateCatalogsResponse
	(*wrapperspb.StringValue)(nil),      // 11: google.protobuf.StringValue
	(*emptypb.Empty)(nil),               // 12: google.protobuf.Empty
}
var file_entpb_entpb_proto_depIdxs = []int32{
	11, // 0: entpb.Catalog.description:type_name -> google.protobuf.StringValue
	2,  // 1: entpb.CreateCatalogRequest.catalog:type_name -> entpb.Catalog
	0,  // 2: entpb.GetCatalogRequest.view:type_name -> entpb.GetCatalogRequest.View
	2,  // 3: entpb.UpdateCatalogRequest.catalog:type_name -> entpb.Catalog
	1,  // 4: entpb.ListCatalogRequest.view:type_name -> entpb.ListCatalogRequest.View
	2,  // 5: entpb.ListCatalogResponse.catalog_list:type_name -> entpb.Catalog
	3,  // 6: entpb.BatchCreateCatalogsRequest.requests:type_name -> entpb.CreateCatalogRequest
	2,  // 7: entpb.BatchCreateCatalogsResponse.catalogs:type_name -> entpb.Catalog
	3,  // 8: entpb.CatalogService.Create:input_type -> entpb.CreateCatalogRequest
	4,  // 9: entpb.CatalogService.Get:input_type -> entpb.GetCatalogRequest
	5,  // 10: entpb.CatalogService.Update:input_type -> entpb.UpdateCatalogRequest
	6,  // 11: entpb.CatalogService.Delete:input_type -> entpb.DeleteCatalogRequest
	7,  // 12: entpb.CatalogService.List:input_type -> entpb.ListCatalogRequest
	9,  // 13: entpb.CatalogService.BatchCreate:input_type -> entpb.BatchCreateCatalogsRequest
	2,  // 14: entpb.CatalogService.Create:output_type -> entpb.Catalog
	2,  // 15: entpb.CatalogService.Get:output_type -> entpb.Catalog
	2,  // 16: entpb.CatalogService.Update:output_type -> entpb.Catalog
	12, // 17: entpb.CatalogService.Delete:output_type -> google.protobuf.Empty
	8,  // 18: entpb.CatalogService.List:output_type -> entpb.ListCatalogResponse
	10, // 19: entpb.CatalogService.BatchCreate:output_type -> entpb.BatchCreateCatalogsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_entpb_entpb_proto_init() }
func file_entpb_entpb_proto_init() {
	if File_entpb_entpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_entpb_proto_rawDesc), len(file_entpb_entpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_entpb_proto_goTypes,
		DependencyIndexes: file_entpb_entpb_proto_depIdxs,
		EnumInfos:         file_entpb_entpb_proto_enumTypes,
		MessageInfos:      file_entpb_entpb_proto_msgTypes,
	}.Build()
	File_entpb_entpb_proto = out.File
	file_entpb_entpb_proto_goTypes = nil
	file_entpb_entpb_proto_depIdxs = nil
}
